-- Load plugins and configurations
require("plugins")
require("settings")
require("lsp")
require("none-ls-config")
require("treesitter")
require("neo-tree-config")
require("neotest-config")
require("utils")
require("keymaps")
