##### ------------------------------------------------------------------
##### Plugins: baseline shared across profiles
##### ------------------------------------------------------------------

# Plugin manager
set -g @plugin 'tmux-plugins/tpm'

# Baseline sane defaults
set -g @plugin 'tmux-plugins/tmux-sensible'
