# Show network speed, battery, then time/date
set -g status-right '#{net_speed} | #{battery_remain} #{battery_percentage} #{battery_icon} | %H:%M %d %b'

# Possible theme mode options:
# set -g @tmux-gruvbox 'dark'
# set -g @tmux-gruvbox 'light'
